<?php
/**
 * Created by PhpStorm.
 * User: Dilusha
 * Date: 4/23/2018
 * Time: 8:38 PM
 */

use PHPUnit\Framework\TestCase;
include '../Driver/DbAccess.php';
class DbAccessTest extends TestCase
{

    public function testLocalDbConnect()
    {
        $db=new DbAccess();
        $db->LocalDbConnect();
    }

    public function testWebServerConnect()
    {

    }

    public function testSaveToLocalDatabase()
    {

    }

    public function testSaveToWebServer()
    {

    }

    public function testQueryWebServer()
    {

    }

    public function testQueryLocalDatabase()
    {

    }

    public function testSetMap()
    {
        $db=new DbAccess();
        $db->SetMap('150DE');
    }


    protected function setUp()/* The :void return type declaration that should be here would cause a BC issue */
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }

    public function test()
    {

    }
}
